using UnityEngine;
using System.Collections;
using System.Collections.Generic;

/*
 * Manage Item
 * Make Items with m_itemInfo_list in GUI Inspector & itemcode is generated by init
 */
public class ItemManager : MonoBehaviour
{
    public static ItemManager instance = null;

    public List<ItemRaw> m_itemInfo_list;

    public void Init_ItemManager()
    {
        for (int i = 0; i < m_itemInfo_list.Count; i++)
        {
            if (m_itemInfo_list[i] == null)
            {
                i++;
                continue;
            }

            ItemRaw inInfo = m_itemInfo_list[i];
            inInfo.m_ItemCode = i;
        }
    }

    public ItemRaw GetItemRawWithItemCode(int itemCode)
    {
        if (itemCode >= m_itemInfo_list.Count)
        {
            Debug.Log("[WARN] : ItemManager::GetItemRawWithItemCode(int itemCode) : out range itemCode");
            return null;
        }

        ItemRaw retItemRaw = m_itemInfo_list[itemCode];
        return retItemRaw;
    }

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else
        {
            Destroy(gameObject);
        }
    }

}
